name: api_rest_dart
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  intl: ^0.18.1
  mysql1: ^0.20.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  string_validator: ^1.0.2
  dart_frog: ^1.0.0
  aquedart: ^5.0.4
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.0.0
